### ISSUE TITLE
Figure.show no longer working

### ISSUE THREAD

**Issue by dradler** [superjax/plotWindow#4]
I'm getting the following error when using the plotWindow figure manager with commands _plt.pause()_ and _plt.show(block=True)_ that used to work when the figures were managed by pyplot:

_FigureCanvasQTAgg object has no attribute 'manager'
Figure.show works only for figures managed by pyplot, normally created by pyplot.figure()._

My code has UI button on one of the figures that is added to one of the tabs and the software needs to wait until this button is pressed before proceeding. Is there a way for the plt.pause or plt.show commands to work with this new figure manager?

**Comment by superjax** [comment]
Have you tried the `pw.show` method, instead of `plt.show()`?

I don't know how plt.pause would interact with this, honestly

**Comment by dradler** [comment]
That worked. I ended up not being able to use the program, for other reasons, but this is solved.
