### ISSUE TITLE
Python crashes if too many plotWindow() have been opened

### ISSUE THREAD

**Issue by davidpagnon** [superjax/plotWindow#7]
Hi, 

Thank you for this wrapper, it is quite useful.
When I open (and then close) a certain amount of plotWindow(), python crashes with error `QGuiApplication::font(): no QGuiApplication instance and no application font set.`

I know very little about PyQt5, and everything I tried did not work. Would you be able to provide this fix?
Thanks in advance.

**Comment by jsjax** [comment]
Can you provide a minimal repro script?

**Comment by davidpagnon** [comment]
Sure! This crashes before the 3rd window is opened.

```
from plotWindow import plotWindow
import matplotlib.pyplot as plt
import numpy as np

for n in range(3):
	pw = plotWindow()
	x = np.arange(0, 10, 0.001)
	for i in range(1,3):
		f = plt.figure()
		ysin = np.sin(i*x)
		plt.plot(x, ysin, '--')
		pw.addPlot(str(i), f)
	pw.show()
```

**Comment by davidpagnon** [comment]
Hi @jsjax, did you have a chance to look at this issue?

**Comment by davidpagnon** [comment]
Issue [posted on stackoverflow](https://stackoverflow.com/questions/77673957/tabbed-matplotlib-plots-qguiapplicationfont-error?noredirect=1#comment136940428_77673957).

**Comment by davidpagnon** [comment]
Fixed almost a full year later, by slightly changing the class plotWindow().
Closing the issue, hoping you can merge it! :)
